---
- hosts: all
  tasks:
  - name: "enable epel testing"
    replace:
      path: /etc/yum.repos.d/epel-testing.repo
      regexp: ^enabled=0
      replace: 'enabled=1'
  - name: "install golang"
    yum: name=golang state=installed
