networks:
  default:
    ipam:
     config:
       - subnet: 192.168.99.0/24

services:
  devbox:
    build: devbox
    volumes:
      - ./:/box:ro
      - ./src:/src:rw
      - /etc/localtime:/etc/localtime:ro
    # required to start x11 programms (run: "xhost +local:" on host)
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    # required for strace / gdb
    cap_add:
        - SYS_PTRACE
    networks:
      default:
        ipv4_address: 192.168.99.99
