---
- hosts: all
  become: true
  become_user: mon
  become_method: su
  become_flags: '-l'
  vars:
    version: "0.7.5"
  tasks:
  - name: "download node_exporter"
    shell: "wget https://github.com/ncabatoff/process-exporter/releases/download/v{{ version }}/process-exporter-{{ version }}.linux-amd64.tar.gz"
    args:
      chdir: /omd/sites/mon/var/tmp
      creates: "/omd/sites/mon/var/tmp/process-exporter-{{ version }}.linux-amd64.tar.gz"
  - name: "unpack node_exporter"
    shell: "tar zxf process-exporter-{{ version }}.linux-amd64.tar.gz"
    args:
      chdir: /omd/sites/mon/var/tmp
      creates: "/omd/sites/mon/var/tmp/process-exporter-{{ version }}.linux-amd64/process-exporter"
  - copy:
      src:  "/omd/sites/mon/var/tmp/process-exporter-{{ version }}.linux-amd64/process-exporter"
      dest: "/omd/sites/mon/local/bin/process-exporter"
      mode:   0755
  - copy:
      src:   /box/devbox/provision/process-exporter/data/process-exporter.yml
      dest:  /omd/sites/mon/etc/process-exporter.yml
      mode:  0644
  - copy:
      src:   /box/devbox/provision/process-exporter/data/init
      dest:  /omd/sites/mon/etc/init.d/process-exporter
      mode:  0755
  - file:
      src: ../init.d/process-exporter
      dest: /omd/sites/mon/etc/rc.d/90-process-exporter
      state: link
  - copy:
      src:   /box/devbox/provision/process-exporter/data/01-process-exporter.yml
      dest:  /omd/sites/mon/etc/prometheus/prometheus.d/scrape_configs/static/01-process-exporter.yml
      mode:  0644
  - name: omd start process-exporter
    shell: "if omd status -b process-exporter >/dev/null; then omd reload process-exporter; else omd start process-exporter; fi"
  - name: omd reload prometheus
    shell: "if omd status -b prometheus >/dev/null; then omd reload prometheus; else omd start prometheus; fi"
  - copy:
      src:   /box/devbox/provision/process-exporter/data/process.json
      dest:  /omd/sites/mon/var/grafana/dashboards/process.json
      mode:  0644
