# clone mod-gearman
---
- hosts: all
  tasks:
  - debug:
      msg: "### mod-gearman-worker.yml"
  - name: "replace mod-gearman-worker-go binary path in init script"
    lineinfile:
        dest: /opt/omd/sites/dev/etc/init.d/gearman_worker
        state: present
        regexp: '^DAEMON'
        line: 'DAEMON=/src/mod-gearman-worker-go/mod_gearman_worker'

  - name: "enable mod-gearman-worker-go prometheus listener"
    lineinfile:
        dest: /opt/omd/sites/dev/etc/mod-gearman/worker.cfg
        state: present
        regexp: 'prometheus_server='
        line: 'prometheus_server=127.0.0.1:9050'

  - name: rebuild mod-gearman-worker-go
    command: make build mod-gearman-worker-go
    args:
      chdir: /src
      creates: /src/mod-gearman-worker-go/mod_gearman_worker
