# clone nagflux
---
- hosts: all
  tasks:
  - name: "replace nagflux binary path in init script"
    lineinfile:
        dest: /opt/omd/sites/dev/etc/init.d/nagflux
        state: present
        regexp: '^DAEMON'
        line: 'DAEMON=/src/nagflux/nagflux'

  - name: rebuild nagflux
    command: make build nagflux
    args:
      chdir: /src
      creates: /src/nagflux/nagflux
