---
- hosts: all
  tasks:
  - debug:
      msg: "### main.yml"
- import_playbook: _common/common.yml

- import_playbook: omd/omd.yml
- import_playbook: apache/apache.yml
- import_playbook: naemon/naemon.yml
- import_playbook: golang/golang.yml
#- import_playbook: process-exporter/process-exporter.yml
#- import_playbook: node-exporter/node-exporter.yml
#- import_playbook: prometheus-nagios-exporter/prometheus-nagios-exporter.yml
- import_playbook: thruk/thruk.yml
- import_playbook: gearmand/gearmand.yml
- import_playbook: mod-gearman/mod-gearman.yml
- import_playbook: mod-gearman-worker-go/mod-gearman-worker-go.yml
- import_playbook: nagflux/nagflux.yml
- import_playbook: histou/histou.yml
- import_playbook: snclient/snclient.yml

# this should be the last regular playbook
- import_playbook: git/git.yml

- hosts: all
  tasks:
  - name: "omd restart mon"
    shell: "omd restart mon"
