---
- hosts: all
  become: true
  become_user: mon
  become_method: su
  become_flags: '-l'
  tasks:
  - name: "git clone nagios-prometheus-exporter"
    command: git clone https://github.com/m-lab/prometheus-nagios-exporter.git
    args:
      chdir: /omd/sites/mon/local/share
      creates: /omd/sites/mon/local/share/prometheus-nagios-exporter/.git

- hosts: all
  tasks:
  - name: "exporter requirements"
    yum: name=python3-flask state=installed
  - name: "add user mon to dev group, so it can read livestatus stats"
    user:
      name=mon
      groups=dev
      append=yes
  - copy: src=/box/devbox/provision/prometheus-nagios-exporter/data/init dest=/omd/sites/mon/etc/init.d/prometheus-nagios-exporter owner=mon group=mon mode=0755
  - file:
      src: ../init.d/prometheus-nagios-exporter
      dest: /omd/sites/mon/etc/rc.d/90-prometheus-nagios-exporter
      owner: mon
      group: mon
      state: link
  - copy: src=/box/devbox/provision/prometheus-nagios-exporter/data/01-prometheus-nagios-exporter.yml dest=/omd/sites/mon/etc/prometheus/prometheus.d/scrape_configs/static/01-prometheus-nagios-exporter.yml owner=mon group=mon mode=0644
  - name: omd start mon prometheus-nagios-exporter
    shell: "if omd status -b prometheus-nagios-exporter >/dev/null; then omd reload prometheus-nagios-exporter; else omd start prometheus-nagios-exporter; fi"
  - name: omd reload mon prometheus
    shell: "if omd status -b prometheus >/dev/null; then omd reload prometheus; else omd start prometheus; fi"
  - copy: src=/box/devbox/provision/prometheus-nagios-exporter/data/livestatus.json dest=/omd/sites/mon/var/grafana/dashboards/livestatus.json owner=mon group=mon mode=0644
