---
- hosts: all
  tasks:
  - copy: src=/box/devbox/provision/node-exporter/data/init dest=/omd/sites/mon/etc/init.d/node-exporter owner=mon group=mon mode=0755
  - file:
      src: ../init.d/node-exporter
      dest: /omd/sites/mon/etc/rc.d/90-node-exporter
      owner: mon
      group: mon
      state: link
  - copy: src=/box/devbox/provision/node-exporter/data/01-node-exporter.yml dest=/omd/sites/mon/etc/prometheus/prometheus.d/scrape_configs/static/01-node-exporter.yml owner=mon group=mon mode=0644
  - name: omd reload mon node-exporter
    shell: "if omd status -b mon node-exporter >/dev/null; then omd reload mon node-exporter; else omd start mon node-exporter; fi"
  - name: omd reload mon prometheus
    shell: "if omd status -b mon prometheus >/dev/null; then omd reload mon prometheus; else omd start mon prometheus; fi"
  - copy: src=/box/devbox/provision/node-exporter/data/node.json dest=/omd/sites/mon/var/grafana/dashboards/node.json owner=mon group=mon mode=0644
