# build gearmand from source
---
- hosts: all
  tasks:
  - debug:
      msg: "### gearmand.yml"
  - name: "gearmand build requirements"
    yum:
      name:
        - libasan
        - libuuid-devel
        - boost-devel
        - sqlite-devel
        - python3-sphinx
        - libevent-devel
        - libpq-devel
      state: installed
  - name: "replace gearmand binary path in init script"
    lineinfile:
        dest: /omd/sites/dev/etc/init.d/gearmand
        state: present
        regexp: '^DAEMON'
        line: 'DAEMON=/src/gearmand/gearmand/gearmand'

  - name: "replace gearmand binary path in init script II"
    lineinfile:
        dest: /omd/sites/dev/etc/init.d/gearmand
        state: present
        regexp: '^# BINARY:'
        line: '# BINARY: /src/gearmand/gearmand/gearmand'

  - name: rebuild gearmand
    command: make build gearmand
    args:
      chdir: /src
      creates: /src/gearmand/gearmand/gearmand
