---
- hosts: all
  vars:
    golang: 1.19.3-2.fc38
    srcurl: https://kojipkgs.fedoraproject.org/packages/golang/1.19.3/2.fc38
  tasks:
  - name: "install golang"
    yum:
        name:
            - golang
        state: installed
  - name: "fetch golang x86 rpm"
    get_url:
        url: "{{ srcurl }}/x86_64/{{ item }}"
        dest: "/tmp/{{ item }}"
    with_items:
        - golang-{{ golang }}.x86_64.rpm
        - golang-bin-{{ golang }}.x86_64.rpm
        - golang-shared-{{ golang }}.x86_64.rpm
  - name: "fetch golang noarch rpm"
    get_url:
        url: "{{ srcurl }}/noarch/{{ item }}"
        dest: "/tmp/{{ item }}"
    with_items:
        - golang-src-{{ golang }}.noarch.rpm
  - name: "install local golang rpms"
    yum:
        name:
            - /tmp/golang-{{ golang }}.x86_64.rpm
            - /tmp/golang-bin-{{ golang }}.x86_64.rpm
            - /tmp/golang-shared-{{ golang }}.x86_64.rpm
            - /tmp/golang-src-{{ golang }}.noarch.rpm
        state: installed
        disable_gpg_check: yes
