---
- include: epel/epel.yml
- include: labs/labs.yml
- hosts: all
  tasks:
  - selinux: state=disabled
  - yum: name=ntp state=installed
  - service: name=ntpd state=started enabled=true
  - timezone: name=Europe/Berlin
  - yum: name=lsof state=installed
  - yum: name=bash-completion,bash-completion-extras state=installed
  - yum: name=telnet state=installed
  - yum: name=git state=installed
  - yum: name=vim state=installed
  - yum: name=gdb state=installed
  - yum: name=valgrind state=installed
  - yum: name=wget state=installed
  - shell: echo -e "*********\nYou can always reprovision by running\n%>sudo bash /vagrant/provision/ansible.sh\n*********\n" > /etc/motd
  - shell: echo "alias la='ls -la'" > /etc/profile.d/dev.sh
- include: omd/omd.yml
- include: apache/apache.yml
- include: naemon/naemon.yml
- include: golang/golang.yml
- include: process-exporter/process-exporter.yml
- include: node-exporter/node-exporter.yml
- include: prometheus-nagios-exporter/prometheus-nagios-exporter.yml
- include: thruk/thruk.yml
- include: mod-gearman/mod-gearman.yml
- include: mod-gearman-worker-go/mod-gearman-worker-go.yml
# this should be the last one
- include: git/git.yml
