# clone thruk
---
- hosts: all
  tasks:
  - name: "thruk build requirements"
    yum: name=make,perl-Module-Install,npm state=installed
  - name: "git clone thruk"
    command: git clone git://github.com/sni/Thruk.git
    args:
      chdir: /src
      creates: /src/Thruk/.git
  - name: "git clone omd_utils"
    command: git clone git://github.com/sni/omd_utils.git
    args:
      chdir: /src
      creates: /src/omd_utils/.git
  - name: "perl Makefile.PL"
    shell: "perl Makefile.PL"
    environment:
      PERL5LIB: '/omd/versions/default/lib/perl5/lib/perl5'
    args:
      chdir: /src/Thruk
      creates: /src/Thruk/Makefile

- hosts: all
  become: true
  become_user: dev
  become_method: su
  become_flags: '-l'
  tasks:
  - name: "install File::ChangeNotify"
    shell: "cpanm -n File::ChangeNotify"
    args:
      creates: /omd/sites/dev/local/lib/perl5/lib/perl5/File/ChangeNotify.pm
  - name: "activate local thruk"
    shell: "yes | /src/omd_utils/thruk_developer/install.sh /src/Thruk"
