# clone thruk
---
- hosts: all
  tasks:
  - debug:
      msg: "### thruk.yml"
  - name: "thruk build requirements"
    yum:
      name:
        - make
        - perl-Module-Install
        - npm
      state: installed
  - name: rebuild thruk
    command: make build thruk
    args:
      chdir: /src
      creates: /src/thruk/Makefile

- hosts: all
  become: true
  become_user: dev
  become_method: su
  become_flags: '-l'
  tasks:
  - name: "activate local thruk"
    shell: "yes | /src/omd_utils/thruk_developer/install.sh /src/thruk"
