# clone mod-gearman
---
- hosts: all
  tasks:
  - name: "mod-gearman build requirements"
    yum:
      name:
        - libasan
        - libtool
        - libtool-ltdl-devel
        - libevent-devel
        - ncurses-devel
        - autoconf
        - autoconf-archive
        - automake
        - openssl-devel
        - cppcheck
      state: installed
  - name: "replace mod-gearman module in naemon config"
    lineinfile:
        dest: /omd/sites/dev/etc/naemon/naemon.d/mod-gearman.cfg
        state: present
        regexp: '^broker_module='
        line: 'broker_module=/src/mod_gearman/mod_gearman_naemon.o config=/omd/sites/dev/etc/mod-gearman/server.cfg'
  - name: rebuild mod_gearman
    command: make build mod_gearman
    args:
      chdir: /src
      creates: /src/mod_gearman/mod_gearman_naemon.o
