# clone mod-gearman
---
- hosts: all
  tasks:
  - name: "mod-gearman build requirements"
    yum:
      name:
        - libtool
        - libtool-ltdl-devel
        - libevent-devel
        - ncurses-devel
        - autoconf
        - automake
        - openssl-devel
      state: installed
  - name: "replace mod-gearman module in naemon config"
    lineinfile:
        dest: /omd/sites/dev/etc/naemon/naemon.d/mod-gearman.cfg
        state: present
        regexp: '^broker_module='
        line: 'broker_module=/src/mod_gearman/mod_gearman_naemon.o config=/omd/sites/dev/etc/mod-gearman/server.cfg'

- hosts: all
  tasks:
  - name: "git clone mod-gearman"
    command: git clone https://github.com/sni/mod_gearman.git
    args:
      chdir: /src
      creates: /src/mod_gearman/.git
  - name: "mod_gearman autogen"
    environment:
      PKG_CONFIG_PATH: '/src/naemon-core/.'
      C_INCLUDE_PATH: '/src/naemon-core/.:/src/naemon-core/src/.'
    shell: "./autogen.sh --with-gearman=/omd/versions/default --enable-debug"
    args:
      chdir: /src/mod_gearman
      creates: /src/mod_gearman/configure
  - name: "make mod_gearman"
    environment:
      PKG_CONFIG_PATH: '/src/naemon-core/.'
      C_INCLUDE_PATH: '/src/naemon-core/.:/src/naemon-core/src/.'
    shell: "./configure --with-gearman=/omd/versions/default --enable-debug; make"
    args:
      chdir: /src/mod_gearman
      creates: /src/mod_gearman/mod_gearman_naemon.o
