# clone naemon-core and naemon-livestatus
---
- hosts: all
  tasks:
  - name: "naemon-core build requirements"
    yum: name=autoconf,automake,pkgconfig,help2man,gperf,libtool,gcc,chrpath,glib2-devel,check,check-devel,perl-Test-Simple state=installed
  - name: "naemon-livestatus build requirements"
    yum:
      name:
        - libasan
        - gcc-c++
        - libicu-devel
        - cppunit-devel
        - python3-flake8
        - python3-behave
      state: installed
  - name: "replace naemon binary path in init script"
    lineinfile:
        dest: /omd/sites/dev/etc/init.d/naemon
        state: present
        regexp: '^DAEMON'
        line: 'DAEMON=/src/naemon-core/src/naemon/naemon'
  - name: "replace naemon binary path in init script II"
    lineinfile:
        dest: /omd/sites/dev/etc/init.d/naemon
        state: present
        regexp: '^# BINARY:'
        line: '# BINARY: .libs/lt-naemon'
  - name: "replace naemon-livestatus path in module config"
    lineinfile:
        dest: /omd/sites/dev/etc/naemon/naemon.d/livestatus.cfg
        state: present
        regexp: '^broker_module'
        line: 'broker_module=/src/naemon-livestatus/src/.libs/livestatus.so num_client_threads=20 pnp_path=/omd/sites/dev/var/pnp4nagios/perfdata /omd/sites/dev/tmp/run/live'
  - name: rebuild naemon-core
    command: make build naemon-core
    args:
      chdir: /src
      creates: /src/naemon-core/src/naemon/.libs/naemon
  - name: rebuild naemon-livestatus
    command: make build naemon-livestatus
    args:
      chdir: /src
      creates: /src/naemon-livestatus/src/.libs/livestatus.so
