# clone thruk
---
- hosts: all
  become: true
  become_user: vagrant
  become_method: su
  become_flags: '-l'
  tasks:
  - name: "git clone thruk"
    command: git clone git://github.com/sni/Thruk.git
    args:
      chdir: /vagrant
      creates: /vagrant/Thruk/.git
  - name: "git clone omd_utils"
    command: git clone git://github.com/sni/omd_utils.git
    args:
      chdir: /vagrant
      creates: /vagrant/omd_utils/.git

- hosts: all
  become: true
  become_user: dev
  become_method: su
  become_flags: '-l'
  tasks:
  - name: "install File::ChangeNotify"
    shell: "cpanm -n File::ChangeNotify"
    args:
      creates: /omd/sites/dev/local/lib/perl5/lib/perl5/File/ChangeNotify.pm
  - name: "activate local thruk"
    shell: "yes | /vagrant/omd_utils/thruk_developer/install.sh /vagrant/Thruk"
